language: node_js
node_js:
  - "8"
before_script:
  - sleep 15
before_install:
  - npm i -g discord.js@11.1.0
  - npm i -g aws-sdk@2.113.0
  - npm i -g dblapi.js@1.2.0
  - npm i -g mongodb@3.0.3
  - npm i -g pokedex-promise-v2@3.1.1
  - npm i -g super-mario-maker-client@0.3.1
  - npm i -g uws@9.14.0
  - openssl aes-256-cbc -K $encrypted_58f547796dc6_key -iv $encrypted_58f547796dc6_iv -in config.json.enc -out config.json -d
cache:
  directories:
    - "node_modules"
services:
  - mongodb
